In [1]:
import numpy

In [2]:
narr = numpy.array([[1,2,3],
                   [0,0,0],
                   [0,0,0]])

In [3]:
narr[-2:1, -2]

array([], dtype=int32)

In [4]:
narr[::2, -1]

array([3, 0])

In [5]:
narr[narr >= 0]

array([1, 2, 3, 0, 0, 0, 0, 0, 0])

In [6]:
narr[narr >= 2]

array([2, 3])

In [7]:
narr > 2

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [8]:
narr < 1

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
marr = narr[-1]
marr

array([0, 0, 0])

In [10]:
marr[1:3] = 1
marr

array([0, 1, 1])

In [11]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 1, 1]])

In [12]:
marr2 = narr.copy

In [13]:
taar = numpy.random.randint(0,10,(4,3))
taar

array([[0, 7, 6],
       [9, 0, 6],
       [2, 2, 6],
       [4, 7, 8]])

In [14]:
taar[1::2,1:2]

array([[0],
       [7]])

In [15]:
taar[0:2:2, -3:-1]

array([[0, 7]])

In [16]:
for r in taar:
    r = r ** 2
    print(r)

[ 0 49 36]
[81  0 36]
[ 4  4 36]
[16 49 64]


In [17]:
taar ** 2

array([[ 0, 49, 36],
       [81,  0, 36],
       [ 4,  4, 36],
       [16, 49, 64]])

In [20]:
for i, r in enumerate(taar):
    print ('Index(' + str(i) + ') is', r)

Index(0) is [0 7 6]
Index(1) is [9 0 6]
Index(2) is [2 2 6]
Index(3) is [4 7 8]


In [29]:
arr = [1, 4, 2, 9, 8, 6, 3]
arr = numpy.array(arr)
arr

array([1, 4, 2, 9, 8, 6, 3])

In [30]:
len(arr)

7

In [31]:
len(arr)//2

3

In [32]:
arr.shape[0]

7

In [33]:
p = arr[len(arr) // 2]
p

9

In [35]:
q = arr[arr.shape[0] // 2]
q

9

In [36]:
l = [x for x in arr if x < p]
l

[1, 4, 2, 8, 6, 3]

In [37]:
r = [x for x in arr if x > p]
r

[]

In [38]:
l1 = arr[arr < p]
l1

array([1, 4, 2, 8, 6, 3])

In [39]:
type(l)

list

In [40]:
type(l1)

numpy.ndarray