In [1]:
import numpy

In [2]:
vector = [1,2,3]

In [3]:
print (type(vector))

<class 'list'>


In [4]:
nvector = numpy.array(vector)
print (type(nvector))

<class 'numpy.ndarray'>


In [5]:
nvector.shape

(3,)

In [6]:
nvector

array([1, 2, 3])

In [7]:
matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]]

In [8]:
nmatrix = numpy.array(matrix)
nmatrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
nmatrix.shape

(4, 3)

In [10]:
i = 3
j = [1,2,3]
k = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
x = [
    [[1,2,3],[6,2,3],[8,4,2]],
    [[5,3,7],[8,2,4],[9,3,2]],
    [[1,3,5],[5,2,8],[3,4,6]]
]

In [11]:
narr = numpy.array([1,2,3])
narr

array([1, 2, 3])

In [12]:
numpy.resize(narr,(2,4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2]])

In [13]:
narr

array([1, 2, 3])

In [14]:
narr.resize((3,3),refcheck=False)

In [15]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
numpy.resize(narr,(1,2))

array([[1, 2]])

In [17]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
matrix = numpy.ones((4,5))
matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
matrix = numpy.zeros((4,4))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
numpy.diag(narr)

array([1, 0, 0])

In [21]:
m1 = numpy.ones((4,5),int)
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
m2 = numpy.zeros((4,5),int)
m2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
numpy.vstack([m1,m2])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
numpy.hstack([m1,m2])

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])

In [25]:
x = numpy.array([1,2,3])
y = numpy.array([4,5,6])

In [26]:
z = x * y
z

array([ 4, 10, 18])

In [27]:
z ** 3

array([  64, 1000, 5832], dtype=int32)

In [28]:
x ** 2

array([1, 4, 9])

In [29]:
x.dot(y)

32

In [30]:
narr = ([1,2,3],[4,5,6],[7,8,9])
naar1 = numpy.array(narr)
naar1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [31]:
naar2 = numpy.array([[1,2,3],
                   [0,0,0],
                   [0,0,0]])
naar2.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [32]:
naar1.astype('f')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [33]:
naar1.sum()

45

In [34]:
naar1.max()

9

In [35]:
naar1.min()

1

In [36]:
naar1.argmax()

8

In [37]:
naar1.argmin()

0

In [38]:
naar1.mean()

5.0

In [39]:
naar1.std()

2.581988897471611

In [40]:
mr = numpy.arange(15) ** 2
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [41]:
mr[2]

4

In [42]:
mr[1:5]

array([ 1,  4,  9, 16])

In [43]:
mr[-3:]

array([144, 169, 196])

In [44]:
mr[2:-3:3]

array([  4,  25,  64, 121])

In [45]:
mr[-10:-2:2]

array([ 25,  49,  81, 121])

In [46]:
mr[5::-2]

array([25,  9,  1])

In [47]:
mr[1:12:-5]

array([], dtype=int32)

In [48]:
mr[11:-1:2]

array([121, 169])

In [49]:
x1 = numpy.array([[1,2,3],
                  [0,0,0,],
                  [0,0,0]])

In [50]:
x1[0:2, 1:3]

array([[2, 3],
       [0, 0]])

In [51]:
x1[::2, -1]

array([3, 0])

In [52]:
x1[::2, -1:]

array([[3],
       [0]])

In [53]:
x1[1:-1:1, 2::2]

array([[0]])

In [54]:
x1[-3:-1, 0::2]

array([[1, 3],
       [0, 0]])

In [55]:
x1[1:-1:2, -1:]

array([[0]])

In [56]:
x1[-1:2, -2]

array([], dtype=int32)

In [57]:
x2 = numpy.array([[1,2,3,4,5],
                 [6,7,8,9,10],
                 [11,12,13,14,15],
                 [16,17,18,19,20]])

In [58]:
x2[2::1, 3:5]

array([[14, 15],
       [19, 20]])

In [59]:
x2[3:-2:2, :]

array([], shape=(0, 5), dtype=int32)