## Quick Sort
یک الگوریتم divide and conquer است. در این الگوریتم یک عنصر به عنوان محور انتخاب شده و آرایه داده شده به آن را در اطراف عنصر انتخاب شده به عنوان محور پارتیشن بندی می کندهدف از پارتیشن ها به این است که با توجه به کل آرایه و عنصر 'x' آرایه که به عنوان محور انتخاب کرده ایم، x را در موقعیت صحیح خود در آرایه قرار می دهید و همه عناصر کوچکتر از x را قبل از x و همه عناصر بزرگتر از x را بعد از x قرارمی دهد. همه اینها در زمان خطی انجام می شود. روش های مختلفی از QuickSort برای انتخاب یک عنصر به عنوان محور وجود دارد : 1. همیشه اولین عنصر را به عنوان محور انتخاب کنید، 2. همیشه آخرین عنصر را به عنوان محور انتخاب کنید، 3. یک عنصر تصادفی را به عنوان محور انتخاب کنید، 4. میانه را به عنوان محور انتخاب کنید. در ادامه این الگوریتم با استفاده از Numpy پیاده سازی شده است. قابل ذکر است که در Numpy عملیات sort به صورت پیشفرض به صورت Quicksort انجام می شود و نیازی به تغییر در تنظیم np.sort نمی باشد.

In [1]:
import numpy as np
i = np.random.randint(0,100,(3,4))
print (i)
j = np.sort(i)
k = np.sort(i,axis=None)
h = np.sort(i,axis=0)
print ('**********')
print (j)
print ('**********')
print (k)
print ('**********')
print (h)


[[ 6 73 26 47]
 [63 47 45 53]
 [50 34 20 65]]
**********
[[ 6 26 47 73]
 [45 47 53 63]
 [20 34 50 65]]
**********
[ 6 20 26 34 45 47 47 50 53 63 65 73]
**********
[[ 6 34 20 47]
 [50 47 26 53]
 [63 73 45 65]]


## Heap Sort
یک الگوریتم مرتب سازی مبتنی بر مقایسه می باشد که بر اساس ساختار داده باینری هیپ است. این الگوریتم شبیه به مرتب سازی انتخاب می باشد که در ابتدا عنصر مینیمم در آرایه را پیدا کرده و در ابتدای آرایه قرار می دهد. سپس این عملیات به همین منوال ادامه پیدا می کند تا تمام عناصر مرتب سازی می گردند. در ادامه این الگوریتم با استفاده از Numpy پیاده سازی شده است. 

In [2]:
import numpy as np
i = np.random.randint(0,100,(3,4))
print (i)
j = np.sort(i,kind='heapsort')
k = np.sort(i,axis=None,kind='heapsort')
h = np.sort(i,axis=0,kind='heapsort')
print ('**********')
print (j)
print ('**********')
print (k)
print ('**********')
print (h)


[[48 52  7 20]
 [67 60 19 41]
 [ 1 44 79 64]]
**********
[[ 7 20 48 52]
 [19 41 60 67]
 [ 1 44 64 79]]
**********
[ 1  7 19 20 41 44 48 52 60 64 67 79]
**********
[[ 1 44  7 20]
 [48 52 19 41]
 [67 60 79 64]]


## Merge Sort
یک الگوریتم divide and conquer است. این الگوریتم شامل تقسیم یک مسئله به چند مسئله فرعی است. الگوریتم به این صورت عمل میکند که آرایه داده شده را به دو زیر آرایه تقریبا مساوی تقسیم می کند. سپس مجددا خود را فراخوانی میکند تا زیر آرایه های جدید به دو قسمت تقریبا مساوی تقسیم گردد. این زیر آرایه های فرعی بارها و بارها به دو نیم تقسیم می شوند تا اینکه در نهایت به زیر آرایه هایی می رسیم که هر کدام فقط یک عنصر دارند. پس از مرتب سازی این زیر آرایه ها ما جفت های مرتب شده از زیر آرایه ها را در یک آرایه مرتب شده نهایی ادغام می کنیم. در ادامه این الگوریتم با استفاده از Numpy پیاده سازی شده است. 

In [3]:
import numpy as np
i = np.random.randint(0,100,(3,4))
print (i)
j = np.sort(i,kind='mergesort')
k = np.sort(i,axis=None,kind='mergesort')
h = np.sort(i,axis=0,kind='mergesort')
print ('**********')
print (j)
print ('**********')
print (k)
print ('**********')
print (h)

[[ 1 40 87 37]
 [95 44 66 41]
 [60 47 63 77]]
**********
[[ 1 37 40 87]
 [41 44 66 95]
 [47 60 63 77]]
**********
[ 1 37 40 41 44 47 60 63 66 77 87 95]
**********
[[ 1 40 63 37]
 [60 44 66 41]
 [95 47 87 77]]
